# For more information, see https://github.com/actions/labeler.

# Add 'documentation' label to any document related changes
documentation:
  - '**/*.{md,txt}'  # markdown and text

# Add 'localisation' label to any translation changes
localisation:
  - '**/lang/**/*'

# Add 'build' label to any build related changes
build:
  - '**/*.gradle'
  - '**/*.properties'
  - '**/fabric.mod.json'  # fabric mod metadata
  - '**/mods.toml'  # forge mod metadata
